# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

formats:
  - pdf
  - epub

python:
  version: "3.11"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  
  commands:
    # Install dependencies
    - pip install -r docs/requirements.txt
    # Build documentation
    - sphinx-build -b html docs/ _readthedocs/html